Document new builder location on ghcr.io (#185)
The commands currently documented download an old version of the builder
which lead to errors during build since the images on Docker Hub still
used cas:
```
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 3.33.152.147:443: i/o timeout"
```